targets:
  $default:
    builders:
      json_serializable:
        options:
          # JSON Serialization options
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      
      freezed:
        options:
          # Freezed options
          union_key: type
          union_value_case: none
      
      injectable_generator:
        options:
          # Injectable options
          auto_register: true
          class_name_pattern: "^_?([A-Z]+.*Service|.*Repository|.*DataSource|.*Client|.*Bloc|.*Cubit)$"
