arb-dir: lib/core/l10n/translations
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/l10n/generated
nullable-getter: false 

